# Generated by Django 4.1.7 on 2023-03-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterId', models.CharField(max_length=255)),
                ('courseId', models.CharField(max_length=255)),
                ('chaptertitle', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=255)),
                ('coursename', models.CharField(max_length=255)),
            ],
        ),
    ]
